[[message]]
old = '''
ああ、覚者さま――
どうか今一度私を――'''
new = 'If you would allow me another chance, Arisen...'
[[message]]
old = '我らはいつも、覚者さまとともに'
new = 'We will be always by your side, Arisen.'
[[message]]
old = '''
覚者さま、お力添えの機会
お待ちしています'''
new = 'I await the opportunity to lend you my strength, Arisen.'
[[message]]
old = '''
覚者さま、どうぞ私にも同伴の許可を
リムストーンからのお声掛けを
お待ちしています'''
new = 'You need only call me from a Riftstone and I will gladly accompany you, Arisen.'
[[message]]
old = '冒険の手助けなら、いつでもいたします'
new = 'I am ready whenever you should need assistance.'
[[message]]
old = 'まだ、作業を承っておりません'
new = 'I have not yet accepted a crafting request.'
[[message]]
old = 'ご指示をお待ちしています'
new = 'I await your orders.'
[[message]]
old = '''
旅かクラフトのご用命あらば
いつでも動きます'''
new = 'I am ready for crafting or an expedition whenever you wish.'
[[message]]
old = '只今作業中ですので、お待ちください'
new = 'I am crafting now. Please wait a while.'
[[message]]
old = '完成まで、いましばらくかかります'
new = 'It will take some time before it is complete.'
[[message]]
old = '集中力を要しますので、会話はまた後ほど'
new = 'I am concentrating now. I will speak with you later.'
[[message]]
old = '''
救っていただき、ありがとうございます
次こそは必ずお役に――！'''
new = 'Thank you for saving me. It will not happen again.'
[[message]]
old = '''
申し訳ありません、覚者さま
精進いたします'''
new = 'I apologize, Arisen. I will devote myself to this task.'
[[message]]
old = '''
次こそご期待を――
この経験を生かします'''
new = 'I have learned from this experience. Next time I will not fail you.'
