[[message]]
old = '''
あ！　か、覚者さま！
こんにちは――'''
new = 'Ah! G-greetings, Arisen.'
[[message]]
old = '覚者――さま――？'
new = 'A...Arisen?'
[[message]]
old = 'こんな自分でよければ、お手伝いを――！'
new = 'I wil aid you in any way I can.'
[[message]]
old = '''
あ、あの――覚者さま！
自分もぜひ、旅のお伴を――！'''
new = 'Er...Arisen!
Might I accompany you as well?'
[[message]]
old = '''
あの、覚者さま！
役に立てることがあれば、自分を――！'''
new = 'Er, Arisen!
If I may be of service...'
[[message]]
old = '出番は――まだ――？'
new = 'Do you have need of me yet?'
[[message]]
old = '少しでも、お手伝いできれば――'
new = 'If there is anything at all I may do to assist...'
[[message]]
old = '自分にも何かできるはず――'
new = 'There must be aught I can do to help.'
[[message]]
old = 'ま、まだできてないんです――'
new = 'I—I'm afraid it's not quite ready yet.'
[[message]]
old = 'あ、慌てると失敗してしまうので――'
new = 'Ah, getting flustered only leads to mistakes...'
[[message]]
old = '''
ここをこう――あ、すみません
集中してたもので'''
new = 'And then this—Oh, apologies.
I was concentrating...'
[[message]]
old = '''
――うぅ、感激です――！
こんな自分を助けに来てくださるなんて――！'''
new = 'Oh...I am overjoyed that you would come rescue one such as myself!'
[[message]]
old = '''
あぁ――
覚者さまの姿を見て、安心しました――
失敗してごめんなさい'''
new = 'Ah...I am relieved to see you Arisen.
I deeply apologize for my error.'
[[message]]
old = '''
良かった――覚者さま！
あれきり会えなくなるかと――'''
new = 'Oh, I am glad, Arisen!
I feared I would never see you again...'
